@echo off
rem
rem This file is generated by the Qt installer
rem
echo Setting up a Qt environment...
set QTDIR=C:\Qt\Qt5.9.3\5.9.3\msvc2015\
echo -- QTDIR set to C:\Qt\Qt5.9.3\5.9.3\msvc2015\
set PATH=C:\Qt\Qt5.9.3\5.9.3\msvc2015\bin;%PATH%
echo -- Added C:\Qt\Qt5.9.3\5.9.3\msvc2015\bin to PATH
set QMAKESPEC=win32-msvc
echo -- QMAKESPEC set to "win32-msvc"
if not "%1"=="vsvars" goto ENDVSVARS
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
:ENDVSVARS
if not "%1"=="vsstart" goto ENDVSSTART
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
devenv /useenv
:ENDVSSTART